import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ProviderTheme from './ProviderTheme'
const inter = Inter({ subsets: ['latin'] })
import Header from './header'
import Loading from './loading'
import { Suspense } from 'react'

export const metadata: Metadata = {
  title: 'Next Monitor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh">
      <body className={inter.className}>
        <Suspense fallback={<Loading/>}>
          <ProviderTheme>
            <Header />
            {children}
          </ProviderTheme>
        </Suspense>
      </body>
    </html>
  )
}
