import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Monitor - Lite',
  description: 'Generated by create next app',
}

export default function LiteLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={`${inter.className}`}>
      <div>
        {children}
      </div>
    </div>
  )
}
